### ISSUE TITLE
对于sdk使用者来说 应该只需要调用 `add_event`, 而不需要关心数据什么时候被sdk丢出去，用户最多的情况下 应该只是程序生命周期结束 强制触发`shutdown`发送内存中还未发送的事件

### ISSUE THREAD

**Issue by zzhutianyu** [TencentBlueKing/bk-audit-python-sdk#3]
https://github.com/TencentBlueKing/bk-audit-python-sdk/blob/ea1b31beb5ae8b0424c1147ff4e1f2cebf2548ac/bk_audit/log/exporters.py#L35

是否 async 应该由sdk的export具体行为决定
程序要求`async`一般的目标是为了数据的处理和发送不block住工作线程 一般的实现都是 提交到一个独立的工作线程去独立处理.
而且这样的方式 对于开发者来说 并不等同于async 只是delay, 还是需要在主流程中进行调用,语义存在明显的差异.
just a comment.

**Comment by OrenZhang** [comment]
#5
