### ISSUE TITLE
sdk 提供的用户使用的直接接口 入参应该尽量明确，如果参数复杂 可以实现`builder`模式 供用户先构建入参 传递进来. 

### ISSUE THREAD

**Issue by zzhutianyu** [TencentBlueKing/bk-audit-python-sdk#4]
https://github.com/TencentBlueKing/bk-audit-python-sdk/blob/ea1b31beb5ae8b0424c1147ff4e1f2cebf2548ac/bk_audit/log/base.py#L82

**Comment by OrenZhang** [comment]
SDK在外层Client有暴露接口给用户并明确参数类型，这里为了减少重复代码所以没有定义，详见 
https://github.com/TencentBlueKing/bk-audit-python-sdk/blob/ea1b31beb5ae8b0424c1147ff4e1f2cebf2548ac/bk_audit/client.py#L109

**Comment by zzhutianyu** [comment]
参数太多了 不要这样设计.

**Comment by zzhutianyu** [comment]
参数多了 两种情况
sdk
- 提供多样的用户接口 add_event_only_content,add_event_with_extra,add_event_with_contect
- 提供入参构造
多参数的接口虽然在python下面可以通过*命名变量单接口提供，对于用户来说需要一定的熟悉
